### ISSUE TITLE
About the traffic light info how to correspond to each TPs?

### ISSUE THREAD

**Issue by zzt007** [SOTIF-AVLab/SinD#11]
Hi, thanks for your great job!
There is a problem about the traffic light info how to correspond to each TPs bothers me a lot, Specifically, at the example 8_2_1 at Tianjin, I want to find out the TPs' corresponding traffic light status during the current period.
![image](https://github.com/user-attachments/assets/ae71d606-1945-4499-904a-3fd245de849f)
belike the picture👆, the red rectangle on the right is the timestamp when the traffic light changed, does it correspond to the left that all the timestamps before the traffic light changed's timestamp are for that traffic light status? 
Looking forward to your early reply :)

**Comment by TheDarkKnight1998** [comment]
The timestamp of each row of traffic lights represents the time point when the status changes to the current state, and it will remain in that state until the time point of the next row

**Comment by zzt007** [comment]
Thanks for your reply, I have processed the traffic light states as the way you said.
